source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '~> 3.3.0'

gem 'rails', '~> 7.2.2'
gem 'pg', '~> 1.5'
gem 'puma', '~> 6.4'
gem 'bcrypt', '~> 3.1.7'
gem 'bootsnap', '>= 1.4.4', require: false
gem 'rack-cors'
gem 'jwt', '~> 2.9'
gem 'lograge'

group :development, :test do
  gem 'debug', platforms: %i[mri windows], require: 'debug/prelude'
  gem 'dotenv-rails'
  gem 'faker', '~> 3.4'
end

group :development do
  gem 'listen', '~> 3.9'
end

gem 'tzinfo-data', platforms: %i[windows jruby]
